apiVersion: v1.1
resources:
  - name: gitPipelinesExamplePythonEnv
    type: GitRepo
    configuration:
      gitProvider: githubAccountGeoffwilliams
      path: declarativesystems/pipelines_example_pythonenv
      branches:
        include: ^{{gitBranch}}$
      cancelPendingRunsOn:
        pullRequestUpdate: true
        newCommit: true
  - name: pythonEnvExample
    type: declarativesystems/PythonEnv
    configuration:
      sourceArtifactory: artifactory # for resolving and publishing packages
      repositoryName: pypi

pipelines:
  - name: pipelinesExamplePythonEnv
    configuration:
      retentionPolicy:
        maxAgeDays: 90
        minRuns: 10
      runtime:
        type: image
        image:
          custom:
            name: "declarativesystems.jfrog.io/docker-local/pipelines"
            tag: "0.9.0"
            registry: artifactory
            sourceRepository: docker-local

    steps:
      - name: pythonBuildAndDeploy
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: pythonEnvExample
            - name: gitPipelinesExamplePythonEnv
        execution:
          onExecute:
            - cd $res_gitPipelinesExamplePythonEnv_resourcePath
            - make publish
